EXPORT ActivityByMonth := RECORD
	UNSIGNED1 Hour;
	UNSIGNED Jan;
	UNSIGNED Feb;
	UNSIGNED Mar;
	UNSIGNED Apr;
	UNSIGNED May;
	UNSIGNED Jun;
	UNSIGNED Jul;
	UNSIGNED Aug;
	UNSIGNED Sep;
	UNSIGNED Oct;
	UNSIGNED Nov;
	UNSIGNED Dec;
END;
		